"""
Train a classifier on pre-encoded dataset.

This script trains an sklearn classifier on pre-encoded embeddings that were
generated by encode_dataset.py. It uses the generic ClassifierTrainer class
which can work with any sklearn or pytorch head model.

Usage:
    python scripts/train_classifier.py

Input:
    - data/processed/encoded_dataset/ (pre-encoded embeddings)

Output:
    - models/classifier.pkl (trained classifier)
"""

import sys
from pathlib import Path
from sklearn import linear_model, tree, ensemble

# Add parent directory to path for imports
sys.path.append(str(Path(__file__).parent.parent))

from utils.classifier_trainer import ClassifierTrainer


def main():
    # Configuration
    encoded_dataset_path = "data/processed/encoded_dataset"
    model_save_path = "models/random_forest_classifier.pkl"
    epochs = 1
    batch_size = 64
    eval_every = 50

    head = ensemble.RandomForestClassifier(random_state=42)

    trainer = ClassifierTrainer(head=head, model_save_path=model_save_path)

    trainer.load_encoded_dataset(encoded_dataset_path)

    trainer.train(epochs=epochs, batch_size=batch_size, eval_every=eval_every)


if __name__ == "__main__":
    main()
